# Generated by Django 5.1.3 on 2024-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
